<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alexandra Tejada-Strop">

<title>Prenatal Mental Health Screening and Postpartum Depressive Symptoms – MADA Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9cdbd49fb92a4d7f9d8c4f710986121f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MADA Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../fitting-exercise/fitting-exercise.html"> 
<span class="menu-text">Fitting Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../presentation-exercise/presentation-exercise.html"> 
<span class="menu-text">Presentation Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../starter-analysis-exercise.html"> 
<span class="menu-text">Starter Analysis Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data-exercise/data-exercise.html"> 
<span class="menu-text">Data Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../tidytuesday-exercise/tidytuesday-exercise.html"> 
<span class="menu-text">Tidy Tuesday</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cdcdata-exercise/cdcdata-exercise.html"> 
<span class="menu-text">CDC Data Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ml-models-exercise/ml-models-exercise.html"> 
<span class="menu-text">ML Models Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../class-project/index.html" aria-current="page"> 
<span class="menu-text">Class Individual Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contacts.html"> 
<span class="menu-text">Contact / Links</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/alex8528/mada-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question"><span class="header-section-number">3</span> Research Question</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">4</span> Methods</a>
  <ul class="collapse">
  <li><a href="#use-of-computational-assistance" id="toc-use-of-computational-assistance" class="nav-link" data-scroll-target="#use-of-computational-assistance"><span class="header-section-number">4.1</span> Use of Computational Assistance</a></li>
  <li><a href="#analysis-approach" id="toc-analysis-approach" class="nav-link" data-scroll-target="#analysis-approach"><span class="header-section-number">4.2</span> Analysis Approach</a></li>
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source"><span class="header-section-number">4.3</span> Data Source</a></li>
  <li><a href="#study-population" id="toc-study-population" class="nav-link" data-scroll-target="#study-population"><span class="header-section-number">4.4</span> Study Population</a></li>
  <li><a href="#measures" id="toc-measures" class="nav-link" data-scroll-target="#measures"><span class="header-section-number">4.5</span> Measures</a></li>
  <li><a href="#statistical-approach" id="toc-statistical-approach" class="nav-link" data-scroll-target="#statistical-approach"><span class="header-section-number">4.6</span> Statistical Approach</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5</span> Results</a>
  <ul class="collapse">
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis"><span class="header-section-number">5.1</span> Exploratory Analysis</a></li>
  <li><a href="#weighted-analysis" id="toc-weighted-analysis" class="nav-link" data-scroll-target="#weighted-analysis"><span class="header-section-number">5.2</span> Weighted Analysis</a></li>
  <li><a href="#interaction-analysis" id="toc-interaction-analysis" class="nav-link" data-scroll-target="#interaction-analysis"><span class="header-section-number">5.3</span> Interaction Analysis</a></li>
  <li><a href="#stratified-analysis" id="toc-stratified-analysis" class="nav-link" data-scroll-target="#stratified-analysis"><span class="header-section-number">5.4</span> Stratified Analysis</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">6</span> Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prenatal Mental Health Screening and Postpartum Depressive Symptoms</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alexandra Tejada-Strop </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Disclaimer: The opinions expressed in this article are the author’s own and do not reflect their employer.</p>
<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>This study explores whether screening for mental health issues during pregnancy is linked to depression after giving birth, using data from the Pregnancy Risk Assessment Monitoring System (PRAMS) Phase 8. It mostly relies on women’s self-reports about their prenatal care and mental health afterward. The researchers used basic statistics and logistic regression to see if there is a connection between screening and postpartum depression, while considering other important factors. They found that women who were screened had lower chances of postpartum depression (OR = 0.76), which is an interesting finding that needs more research. Since the data is based on self-reports and observational, the results should be interpreted with caution.</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>Postpartum depression is an important health issue that affects a mother’s well-being, family life, and the baby’s health <span class="citation" data-cites="bauman2020vitalsigns">Bauman et al. (<a href="#ref-bauman2020vitalsigns" role="doc-biblioref">2020</a>)</span>. Guidelines now recommend regular screening for depression and anxiety during pregnancy and after birth <span class="citation" data-cites="acog2023screening">American College of Obstetricians and Gynecologists (<a href="#ref-acog2023screening" role="doc-biblioref">2023</a>)</span>; <span class="citation" data-cites="uspstf2019perinatal">U.S. Preventive Services Task Force (<a href="#ref-uspstf2019perinatal" role="doc-biblioref">2019</a>)</span>. Even with these guidelines, it is still unclear whether screening for mental health during pregnancy actually reduces the number of postpartum depression cases overall. Most evidence comes from clinical or intervention studies, with less data from general populations. Mental health during pregnancy and after birth is a key part of a mother’s overall health. Poor mental health during this time can cause problems for both mothers and babies, like difficulty caring for oneself and issues with early child development <span class="citation" data-cites="acog2023screening">American College of Obstetricians and Gynecologists (<a href="#ref-acog2023screening" role="doc-biblioref">2023</a>)</span>. Because of this, healthcare providers are encouraged to check mental health regularly throughout pregnancy and after delivery. Screening during pregnancy might help find women who are already showing symptoms or are at higher risk of postpartum depression. But we do not have enough population-level data to fully understand how prenatal screening relates to postpartum depression, and learning more about this could improve clinical care and public health policies. This study uses data from PRAMS, a surveillance system run by the CDC together with state health departments <span class="citation" data-cites="cdc_prams_phase8_codebook">Centers for Disease Control and Prevention (<a href="#ref-cdc_prams_phase8_codebook" role="doc-biblioref">2024a</a>)</span>; <span class="citation" data-cites="cdc_prams_phase8_topics">Centers for Disease Control and Prevention (<a href="#ref-cdc_prams_phase8_topics" role="doc-biblioref">2024b</a>)</span>. PRAMS gathers survey responses from women who recently had a live birth and links these responses with birth certificate data. The survey asks about their experiences before, during, and after pregnancy, including prenatal care, health behaviors, mental health, and postpartum results. Forty-six states, the District of Columbia, New York City, the Northern Mariana Islands, and Puerto Rico participate, covering 81% of all births in the U.S. With thousands of responses, PRAMS provides valuable data for research and model building.</p>
</section>
<section id="research-question" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Research Question</h1>
<p>Do women who are asked about depression or anxiety during prenatal visits less often experience postpartum depression? The main thing we look at is whether women say they felt depressed or lost interest after giving birth, based on survey questions. The key factor is whether healthcare providers asked about mental health during pregnancy. Other factors include depression during pregnancy and the mother’s education level.</p>
</section>
<section id="methods" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Methods</h1>
<section id="use-of-computational-assistance" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="use-of-computational-assistance"><span class="header-section-number">4.1</span> Use of Computational Assistance</h2>
<p>ChatGPT was used to help troubleshoot parts of the code. All analyses, decisions, and interpretations were reviewed and completed by the author.</p>
</section>
<section id="analysis-approach" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="analysis-approach"><span class="header-section-number">4.2</span> Analysis Approach</h2>
<p>We first compared people who reported having prenatal mental health screening with those who did not. This helped us check the data quality, find missing details, and spot early patterns. Then, we used statistical methods to look at the link between prenatal screening and postpartum depression, considering important factors.</p>
</section>
<section id="data-source" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="data-source"><span class="header-section-number">4.3</span> Data Source</h2>
<p>This data comes from PRAMS, a survey run by the Centers for Disease Control and Prevention and state health departments. PRAMS collects information people share about their experiences before, during, and shortly after pregnancy. Because PRAMS uses a detailed survey, the data can be analyzed with special variables included in the dataset. The main analyses here are unweighted, but a weighted analysis using PRAMS survey weights is also included to check how applicable the results are to the general population.</p>
</section>
<section id="study-population" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="study-population"><span class="header-section-number">4.4</span> Study Population</h2>
<p>The full PRAMS analytic dataset included 235,304 respondents. After excluding observations with missing values for the primary exposure, outcome, and selected covariates, the final analytic sample included 233,213 respondents. Complete case analysis was used, which might cause bias if data are not missing completely at random. Respondents with missing data might differ in important ways from those with complete data, potentially affecting how well the results apply to other groups. Table 1 summarizes the characteristics of the study population.</p>
<div class="cell">
<div id="tbl-study-pop" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study-pop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Study population characteristics
</figcaption>
<div aria-describedby="tbl-study-pop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Characteristic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sample size</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total respondents</td>
<td style="text-align: right;">235,304</td>
<td style="text-align: right;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Respondents in analytic sample</td>
<td style="text-align: right;">233,213</td>
<td style="text-align: right;">99.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prenatal screening</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Screened during prenatal care</td>
<td style="text-align: right;">189,220</td>
<td style="text-align: right;">81.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not screened during prenatal care</td>
<td style="text-align: right;">43,993</td>
<td style="text-align: right;">18.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Postpartum depressive symptoms</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: right;">200,334</td>
<td style="text-align: right;">85.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">32,879</td>
<td style="text-align: right;">14.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Depression during pregnancy</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">37,444</td>
<td style="text-align: right;">16.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: right;">195,769</td>
<td style="text-align: right;">83.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maternal education</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Less than high school</td>
<td style="text-align: right;">6,279</td>
<td style="text-align: right;">2.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">High school graduate</td>
<td style="text-align: right;">19,886</td>
<td style="text-align: right;">8.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some college</td>
<td style="text-align: right;">55,502</td>
<td style="text-align: right;">23.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">College graduate</td>
<td style="text-align: right;">65,872</td>
<td style="text-align: right;">28.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">More than college</td>
<td style="text-align: right;">85,674</td>
<td style="text-align: right;">36.7%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="measures" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="measures"><span class="header-section-number">4.5</span> Measures</h2>
<p>The main exposure was whether a healthcare provider talked about depression or anxiety during prenatal visits, based on a survey question. This was recorded as yes or no. The main outcome was postpartum depressive symptoms, measured using survey questions about feelings of depression and loss of interest after childbirth. These questions have been used before in research on postpartum depression <span class="citation" data-cites="bauman2020vitalsigns">Bauman et al. (<a href="#ref-bauman2020vitalsigns" role="doc-biblioref">2020</a>)</span>; <span class="citation" data-cites="farr2016provider">Farr et al. (<a href="#ref-farr2016provider" role="doc-biblioref">2016</a>)</span>. Key factors were depression during pregnancy and the mother’s education level. Depression during pregnancy was included because women who have had depression before are more likely to have depressive symptoms after giving birth. The mother’s education was included because it can affect access to healthcare and mental health.</p>
</section>
<section id="statistical-approach" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="statistical-approach"><span class="header-section-number">4.6</span> Statistical Approach</h2>
<p>Exploratory analysis included basic statistics, cross-tabulation, and bar charts to compare postpartum depression symptoms based on screening status. All of this was done using R.</p>
<p>A multivariable logistic regression was used to see if postpartum depression symptoms were related to prenatal mental health screening. We also considered depression during pregnancy and maternal education as additional factors. The results are shown as odds ratios with 95% confidence intervals.</p>
<p>A random forest model was also run as a sensitivity check to assess whether a more flexible approach improved predictions over logistic regression. Full model validation results are reported in the Supplemental Materials.</p>
<p>To account for the PRAMS survey design, a weighted logistic regression was run using the survey package in R, incorporating survey weights, cluster IDs, and strata variables to produce population-representative estimates.</p>
<p>To see if the effect of screening was different for women who did or did not have depression during pregnancy, we added an interaction term between screening and depression. Lastly, separate logistic regressions were run for women with and without depression during pregnancy to examine the effect of screening within each group.</p>
</section>
</section>
<section id="results" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Results</h1>
<p>The analytic sample included 233,213 respondents. Overall, 81.1% reported being screened for depression during prenatal care, and 14.1% reported postpartum depressive symptoms.</p>
<section id="exploratory-analysis" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="exploratory-analysis"><span class="header-section-number">5.1</span> Exploratory Analysis</h2>
<p>Postpartum depression was a bit more common among women who were not screened, at 15.1%, compared to 13.9% for those who were. Women who had depression during pregnancy also showed higher rates. There were clear differences across education levels. Table 2 shows that, before adjusting for other factors, women who were screened already had lower chances of postpartum depression than those who were not.</p>
<div class="cell">
<div id="tbl-bivariate" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Unadjusted odds ratio for prenatal mental health screening and postpartum depressive symptoms
</figcaption>
<div aria-describedby="tbl-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Odds ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">P value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prenatal mental health screening</td>
<td style="text-align: center;">0.91</td>
<td style="text-align: center;">(0.88, 0.93)</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note:</span> <sup></sup> Unadjusted model. Reference group: not screened during prenatal care.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>Before considering other factors, the respondents who were screened already had lower chances of postpartum depression compared to those who were not screened. Table 3 presents the adjusted odds ratio for all predictors in the model.</p>
<div class="cell">
<div id="tbl-multivariable" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multivariable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Adjusted odds ratios for factors associated with postpartum depressive symptoms
</figcaption>
<div aria-describedby="tbl-multivariable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Odds ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">P value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prenatal mental health screening</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">(0.74, 0.78)</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Depression during pregnancy</td>
<td style="text-align: center;">3.38</td>
<td style="text-align: center;">(3.29, 3.47)</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education: High school graduate</td>
<td style="text-align: center;">1.36</td>
<td style="text-align: center;">(1.25, 1.48)</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education: Some college</td>
<td style="text-align: center;">1.29</td>
<td style="text-align: center;">(1.19, 1.39)</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education: College graduate</td>
<td style="text-align: center;">1.09</td>
<td style="text-align: center;">(1.01, 1.18)</td>
<td style="text-align: center;">0.034</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education: More than college</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">(0.64, 0.75)</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note:</span> <sup></sup> Reference groups: not screened during prenatal care, no depression during pregnancy, less than high school education.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-screening" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-screening-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/screening_vs_postpartum_depression.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-screening-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Postpartum depressive symptoms by prenatal mental health screening
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 1 shows the distribution of postpartum depressive symptoms by prenatal screening status.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-depression-pregnancy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-depression-pregnancy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/depression_pregnancy_vs_postpartum.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-depression-pregnancy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Postpartum depressive symptoms by depression during pregnancy
</figcaption>
</figure>
</div>
</div>
</div>
<p>Women who experience depression during pregnancy are more likely to have postpartum depression. About 31 out of 100 women with depression during pregnancy also had postpartum depression, compared to about 11 out of 100 women who did not experience depression.</p>
<div class="cell">
<div id="tbl-screening" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-screening-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Distribution of postpartum depressive symptoms by prenatal mental health screening
</figcaption>
<div aria-describedby="tbl-screening-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Screening status</th>
<th style="text-align: center;">Depressive symptoms</th>
<th style="text-align: center;">No depressive symptoms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Not screened</td>
<td style="text-align: center;">6,641 (15.1%)</td>
<td style="text-align: center;">37,352 (84.9%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Screened</td>
<td style="text-align: center;">26,238 (13.9%)</td>
<td style="text-align: center;">162,982 (86.1%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Table 4 shows that 15.1% of respondents who were not screened reported postpartum depression symptoms, compared to 13.9% of those who were screened. This aligns with the results from the adjusted model.</p>
</section>
<section id="weighted-analysis" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="weighted-analysis"><span class="header-section-number">5.2</span> Weighted Analysis</h2>
<p>To see if the results apply to the wider group of new mothers, the main model was re-run using survey weights from PRAMS. The results were similar to the original analysis without weights. Women who were screened had lower chances of postpartum depression (OR = 0.79, 95% CI: 0.75 to 0.82, p &lt; 0.001), and depression during pregnancy was a strong predictor (OR = 3.46, 95% CI: 3.30 to 3.62, p &lt; 0.001). The similarity between weighted and unweighted results suggests the original findings are likely representative of the larger population.</p>
<div class="cell">
<div id="tbl-weighted-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-weighted-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Comparison of unweighted and weighted odds ratios for main predictors
</figcaption>
<div aria-describedby="tbl-weighted-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Unweighted OR (95% CI)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Weighted OR (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prenatal mental health screening</td>
<td style="text-align: center;">0.76 (0.74, 0.78)</td>
<td style="text-align: center;">0.79 (0.75, 0.82)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Depression during pregnancy</td>
<td style="text-align: center;">3.38 (3.29, 3.47)</td>
<td style="text-align: center;">3.46 (3.30, 3.62)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education: High school graduate</td>
<td style="text-align: center;">1.36 (1.25, 1.48)</td>
<td style="text-align: center;">1.41 (1.23, 1.62)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education: Some college</td>
<td style="text-align: center;">1.29 (1.19, 1.39)</td>
<td style="text-align: center;">1.29 (1.13, 1.48)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education: College graduate</td>
<td style="text-align: center;">1.09 (1.01, 1.18)</td>
<td style="text-align: center;">1.12 (0.99, 1.28)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education: More than college</td>
<td style="text-align: center;">0.69 (0.64, 0.75)</td>
<td style="text-align: center;">0.70 (0.61, 0.80)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="interaction-analysis" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="interaction-analysis"><span class="header-section-number">5.3</span> Interaction Analysis</h2>
<p>To see if the effect of prenatal screening was different for women with a history of depression during pregnancy, an interaction term was added to the model. The results showed that there was no significant difference between the groups (OR = 1.02, 95% CI: 0.95 to 1.10, p = 0.58). This suggests that the protective effect of screening is similar for women regardless of their depression history during pregnancy.</p>
</section>
<section id="stratified-analysis" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="stratified-analysis"><span class="header-section-number">5.4</span> Stratified Analysis</h2>
<p>Logistic regression analysis showed that women who were screened during pregnancy had lower chances of experiencing postpartum depression, whether or not they had depression during pregnancy. For women without depression, the odds were about 24% lower, and for those with depression, about 23% lower. These findings suggest that screening during pregnancy can be helpful for all women, no matter their mental health history.</p>
</section>
</section>
<section id="discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Discussion</h1>
<p>This study looked at whether screening for mental health issues during pregnancy was linked to a lower risk of depression after giving birth, based on PRAMS data. Women who were screened were less likely to experience postpartum depression, even when accounting for past depression and their education. However, since this was an observational study, we cannot be certain that the screening directly caused the lower depression rates. One reason might be that screening helps women understand mental health concerns better and encourages them to seek help early, connecting them with support before delivery. Another reason could be that screening identifies women who were already more at risk for depression, which might show up later regardless of what actions were taken.</p>
<p>These findings are broadly consistent with prior work showing that postpartum depressive symptoms are common and that provider screening practices vary <span class="citation" data-cites="bauman2020vitalsigns">Bauman et al. (<a href="#ref-bauman2020vitalsigns" role="doc-biblioref">2020</a>)</span>; <span class="citation" data-cites="farr2016provider">Farr et al. (<a href="#ref-farr2016provider" role="doc-biblioref">2016</a>)</span>. Clinical guidelines recommend routine screening during pregnancy and postpartum <span class="citation" data-cites="acog2023screening">American College of Obstetricians and Gynecologists (<a href="#ref-acog2023screening" role="doc-biblioref">2023</a>)</span>, and these results add to the population-level evidence on how screening relates to reported symptoms.</p>
<p>The biggest thing we found was how strongly depression during pregnancy predicted postpartum depression symptoms. Women who experienced depression while pregnant were more than three times as likely to have postpartum symptoms (OR = 3.38, weighted OR = 3.46). This shows how important it is to consider mental health history when looking at postpartum outcomes. Interestingly, the analysis showed that the protective effect of screening was similar for women with and without depression during pregnancy (OR = 1.02, p = 0.58). The separate analysis confirmed this, with similar screening ORs in both groups (0.76 and 0.77). These results support universal mental health screening during pregnancy rather than only focusing on high-risk women.</p>
<p>It is important to remember what this study cannot tell us. Since the data come from just one point in time and are based on women’s own reports, we cannot say if screening directly led to better results. Women who were screened might have had better access to healthcare or more support from providers, which could also affect postpartum mental health.</p>
<p><strong>Strengths:</strong> PRAMS is a large dataset that includes data from multiple states, providing enough information for detailed analysis and making the results more relevant across different areas than studies from just one place.</p>
<p><strong>Limitations:</strong> The data come from self-reports, which can be affected by memory errors. The measure for postpartum depression symptoms is not a hospital diagnosis. Since the data are from one point in time, it is hard to know what causes what. Also, there are factors we did not measure, like whether someone has insurance, their social support, or how healthcare providers deliver care, which could influence the results.</p>
<p>In future research, including details like insurance status, access to mental health services, and income could be helpful. This study also used weighted analysis with PRAMS survey weights, and the results matched the unweighted estimates, which supports that the findings can be applied more broadly.</p>
</section>
<section id="references" class="level1" data-number="7">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">7 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-acog2023screening" class="csl-entry" role="listitem">
American College of Obstetricians and Gynecologists. (2023). <em>Screening and diagnosis of mental health conditions during pregnancy and postpartum</em>. <a href="https://www.acog.org/clinical/clinical-guidance/clinical-practice-guideline/articles/2023/06/screening-and-diagnosis-of-mental-health-conditions-during-pregnancy-and-postpartum">https://www.acog.org/clinical/clinical-guidance/clinical-practice-guideline/articles/2023/06/screening-and-diagnosis-of-mental-health-conditions-during-pregnancy-and-postpartum</a>
</div>
<div id="ref-bauman2020vitalsigns" class="csl-entry" role="listitem">
Bauman, B. L., Ko, J. Y., Cox, S., D’Angelo, D. V., Warner, L., Folger, S. G., Tevendale, H. D., Rockhill, K. M., Galang, R. R., Barfield, W. D., Kroelinger, C. D., &amp; Morrow, B. (2020). Vital signs: Postpartum depressive symptoms and provider discussions about perinatal depression — united states, 2018. <em>Morbidity and Mortality Weekly Report</em>, <em>69</em>(19), 575–581. <a href="https://doi.org/10.15585/mmwr.mm6919a2">https://doi.org/10.15585/mmwr.mm6919a2</a>
</div>
<div id="ref-cdc_prams_phase8_codebook" class="csl-entry" role="listitem">
Centers for Disease Control and Prevention. (2024a). <em>Phase 8 automated research file codebook</em>. <a href="https://www.cdc.gov/prams/php/data-research/codebooks-phase-8.html">https://www.cdc.gov/prams/php/data-research/codebooks-phase-8.html</a>
</div>
<div id="ref-cdc_prams_phase8_topics" class="csl-entry" role="listitem">
Centers for Disease Control and Prevention. (2024b). <em>PRAMS phase 8 topic reference document</em>. <a href="https://www.cdc.gov/prams/pdf/questionnaire/phase-8-topics-reference_508tagged.pdf">https://www.cdc.gov/prams/pdf/questionnaire/phase-8-topics-reference_508tagged.pdf</a>
</div>
<div id="ref-farr2016provider" class="csl-entry" role="listitem">
Farr, S. L., Dietz, P. M., O’Hara, M. W., Burley, K., Ko, J. Y., &amp; Gibbs Pickens, C. M. (2016). Provider communication on perinatal depression: A population-based study. <em>Archives of Women’s Mental Health</em>, <em>19</em>(1), 35–40. https://doi.org/<a href="https://doi.org/10.1089/jwh.2013.4438">https://doi.org/10.1089/jwh.2013.4438</a>
</div>
<div id="ref-uspstf2019perinatal" class="csl-entry" role="listitem">
U.S. Preventive Services Task Force. (2019). <em>Perinatal depression: Preventive interventions</em>. <a href="https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/perinatal-depression-preventive-interventions">https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/perinatal-depression-preventive-interventions</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>